export const SHOW_STATES_LOADING = 'SHOW_STATES_LOADING';
export const HIDE_STATES_LOADING = 'HIDE_STATES_LOADING';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_ERROR = 'GET_STATES_ERROR';

export const SHOW_SUBJECTS_LOADING = 'SHOW_SUBJECTS_LOADING';
export const HIDE_SUBJECTS_LOADING = 'HIDE_SUBJECTS_LOADING';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_ERROR = 'GET_SUBJECTS_ERROR';

export const SHOW_QUALIFICATIONS_LOADING = 'SHOW_QUALIFICATIONS_LOADING';
export const HIDE_QUALIFICATIONS_LOADING = 'HIDE_QUALIFICATIONS_LOADING';
export const GET_QUALIFICATIONS_SUCCESS = 'GET_QUALIFICATIONS_SUCCESS';
export const GET_QUALIFICATIONS_ERROR = 'GET_QUALIFICATIONS_ERROR';
