export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';
export const CREATE_EXAM_ERROR = 'CREATE_EXAM_ERROR';

export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS';
export const GET_EXAMS_ERROR = 'GET_EXAMS_ERROR';

export const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
export const GET_EXAM_ERROR = 'GET_EXAM_ERROR';

export const UPDATE_EXAM_SUCCESS = 'UPDATE_EXAM_SUCCESS';
export const UPDATE_EXAM_ERROR = 'UPDATE_EXAM_ERROR';

export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_ERROR = 'DELETE_EXAM_ERROR';

export const EXAM_SHOW_LOADING = 'EXAM_SHOW_LOADING';