export const CREATE_MODULE_SUCCESS = 'CREATE_MODULE_SUCCESS';
export const CREATE_MODULE_ERROR = 'CREATE_MODULE_ERROR';

export const GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS';
export const GET_MODULES_ERROR = 'GET_MODULES_ERROR';

export const GET_MODULE_SUCCESS = 'GET_MODULE_SUCCESS';
export const GET_MODULE_ERROR = 'GET_MODULE_ERROR';

export const UPDATE_MODULE_SUCCESS = 'UPDATE_MODULE_SUCCESS';
export const UPDATE_MODULE_ERROR = 'UPDATE_MODULE_ERROR';

export const DELETE_MODULE_SUCCESS = 'DELETE_MODULE_SUCCESS';
export const DELETE_MODULE_ERROR = 'DELETE_MODULE_ERROR';

export const MODULE_SHOW_LOADING = 'MODULE_SHOW_LOADING';