export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';

export const SHOW_AUTHENTICATION_LOADING = 'SHOW_AUTHENTICATION_LOADING';
export const HIDE_AUTHENTICATION_LOADING = 'HIDE_AUTHENTICATION_LOADING';

export const FETCH_USER_PROFILES_ERROR = 'FETCH_USER_PROFILES_ERROR';
export const FETCH_USER_PROFILES_SUCCESS = 'FETCH_USER_PROFILES_SUCCESS';

export const SIGNOUT_USER = 'SIGNOUT_USER';

export const RESET_USER_STATUS = 'RESET_USER_STATUS';
